// Mocks generated by Mockito 5.3.2 from annotations
// in adviser/test/application/adviser/adviser_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:adviser/domain/entities/advise_entity.dart' as _i6;
import 'package:adviser/domain/failures/failures.dart' as _i7;
import 'package:adviser/domain/repositories/adviser_repository.dart' as _i2;
import 'package:adviser/domain/usecases/adviser_usecases.dart' as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdviserRepository_0 extends _i1.SmartFake
    implements _i2.AdviserRepository {
  _FakeAdviserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdviserUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdviserUseCases extends _i1.Mock implements _i4.AdviserUseCases {
  MockAdviserUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AdviserRepository get adviserRepository => (super.noSuchMethod(
        Invocation.getter(#adviserRepository),
        returnValue: _FakeAdviserRepository_0(
          this,
          Invocation.getter(#adviserRepository),
        ),
      ) as _i2.AdviserRepository);
  @override
  _i5.Future<_i3.Either<_i6.AdviseEntity, _i7.Failure>> getAdvise() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdvise,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.AdviseEntity, _i7.Failure>>.value(
                _FakeEither_1<_i6.AdviseEntity, _i7.Failure>(
          this,
          Invocation.method(
            #getAdvise,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.AdviseEntity, _i7.Failure>>);
}
